Added an ability to view an article.
XashDM/sport-hub pull request #22
Opened 2021-08-27 15:01 UTC by SerhiyToroniy

2021-08-30 11:51 UTC, XashDM commented on sports_hub/sports_hub/Views/Article/Index.cshtml
> +                    if (counter < 3)
Magic number - set it in ViewBag and 3 should be constant

2021-08-30 12:12 UTC, XashDM commented on sports_hub/sports_hub/Controllers/ArticleController.cs
> +        public ArticleController(ApplicationContext aC)
give full name to parameter, not aC

2021-08-30 12:12 UTC, XashDM commented on sports_hub/sports_hub/Controllers/ArticleController.cs
> +        private readonly ApplicationContext applicationContext;
add new line after private field

2021-08-30 12:17 UTC, XashDM commented on sports_hub/sports_hub/Controllers/ArticleController.cs
> +            ICollection<Article> moreArticles = new List<Article>();
Use var or directly List<Article>

2021-08-30 21:54 UTC, ZarechOleksii requested changes

2021-08-30 21:54 UTC, ZarechOleksii commented on sports_hub/sports_hub/Controllers/ArticleController.cs
> +            foreach (var item in _applicationContext.Articles)
Чому шукаєш через цикл? Можна використати_applicationContext.Articles.Find() який знайде потрібну статтю

2021-08-30 21:54 UTC, ZarechOleksii commented on sports_hub/sports_hub/Controllers/ArticleController.cs
> +                    foreach (var i in _applicationContext.Articles)
Це все можна набагато краще зробити за допомогою linq, викинути один той що ми не показуємо за допомогою where, перевірити на Published теж за допомогою where, взяти тільки статті певної категорії за допомогою where і взяти лише певну їх кількість за допомогою take (працює як limit або top в SQL).

2021-08-31 18:45 UTC, ZarechOleksii approved these changes

2021-08-31 18:45 UTC, ZarechOleksii commented on sports_hub/sports_hub/Controllers/ArticleController.cs
> +                var mainArticle = _applicationContext.Articles.ToList().Find(c=>c.Id==id);
Команда ToList() змушує базу моментально повернути нам список всіх статтей, але нам це не потрібно, нам потрібно всього лише взяти оддну з них, тому метод ToList() можга просто забрати.

2021-08-31 19:21 UTC, SerhiyToroniy commented on sports_hub/sports_hub/Controllers/ArticleController.cs
> +                var mainArticle = _applicationContext.Articles.ToList().Find(c=>c.Id==id);
If ToList() is removed, there is the compilation error and it's impossible to paste any predicat there.

2021-09-01 12:12 UTC, merged