Display the Main articles section for site users on the Home page.
XashDM/sport-hub pull request #32
Opened 2021-09-04 16:21 UTC by SerhiyToroniy

2021-09-05 10:43 UTC, MariaPonomarenko38 commented on sports_hub/sports_hub/Controllers/HomeController.cs
> +            const int mainArticlesCount = 5;
you can remove it, admin can't add more than 5 articles

2021-09-05 11:40 UTC, MariaPonomarenko38 requested changes

2021-09-05 11:40 UTC, MariaPonomarenko38 commented on sports_hub/sports_hub/Models/Entities/Navigation/Article.cs
> +        public bool IsMainArticle { get; set; }
change IsMainArticle field on `public StatusType StatusMainArticle { get; set; }`
add enum type before Article class `public enum StatusType
    {
        Published,
        Saved,
        None
    }`

2021-09-05 11:40 UTC, MariaPonomarenko38 commented on sports_hub/sports_hub/Models/Entities/Navigation/Article.cs
>      }
add field `public bool ShowOnMainPage { get; set; }`

2021-09-05 11:40 UTC, MariaPonomarenko38 commented on sports_hub/sports_hub/Controllers/HomeController.cs
> +            var mainArticles = _context.Articles.Where(i => i.Published && i.IsMainArticle).Take(mainArticlesCount).ToList<Article>();
change on this `var mainArticles = _context.Articles.Where(i => i.Published && i.StatusMainArticle==StatusType.Published).Take(mainArticlesCount).ToList<Article>();`

2021-09-05 17:20 UTC, MariaPonomarenko38 approved these changes

2021-09-06 07:04 UTC, MariaPonomarenko38 requested changes

2021-09-06 07:04 UTC, MariaPonomarenko38 commented on sports_hub/sports_hub/Controllers/HomeController.cs
> +            var mainArticles = _context.Articles.Where(i => i.Published && i.StatusMainArticle == StatusType.Published).ToList<Article>();
check if ShowOnMainPage property is true

2021-09-06 07:09 UTC, MariaPonomarenko38 commented on sports_hub/sports_hub/Controllers/HomeController.cs
> +            var mainArticles = _context.Articles.Where(i => i.Published && i.StatusMainArticle == StatusType.Published).ToList<Article>();
`var mainArticles = _context.Articles.Where(i => i.Published && i.StatusMainArticle == StatusType.Published && i.ShowOnMainPage).ToList<Article>();`

2021-09-06 07:47 UTC, MariaPonomarenko38 approved these changes

2021-09-07 06:53 UTC, LIUBOMYR-HOLKO commented on sports_hub/sports_hub/Controllers/HomeController.cs
> +            ViewBag.MainArticleCategoryName = mainArticle.CategoryName;
if mainArticle is null will be an exception.

2021-09-07 07:04 UTC, LIUBOMYR-HOLKO commented on sports_hub/sports_hub/Controllers/HomeController.cs
> +            ViewBag.MainArticleImage = System.IO.File.ReadAllBytes("wwwroot/images/Account/sing_up_in.png");
hardcode here. Every article will have the same image

2021-09-07 09:50 UTC, XashDM approved these changes
Fix comments

2021-09-07 09:50 UTC, XashDM commented on sports_hub/sports_hub/Models/Entities/Navigation/Article.cs
> +        public DateTime dateTime { get; set; }
Uppercase

2021-09-07 09:50 UTC, XashDM commented on sports_hub/sports_hub/wwwroot/js/HomeScript.js
> +//let news = document.getElementsByClassName('mini-news');
remove

2021-09-07 18:50 UTC, merged