add footer configuration functionality
XashDM/sport-hub pull request #6
Opened 2021-08-08 14:15 UTC by MariaPonomarenko38

2021-08-09 19:33 UTC, XashDM commented on sports_hub/sports_hub/Views/AdminPage/FooterConfig/_MainPartFooterPartial.cshtml
> +        @{ foreach (var page1 in Model)
Магічна назва

2021-08-09 19:35 UTC, XashDM commented on sports_hub/sports_hub/Views/AdminPage/FooterConfig/_EditFormFooterPartial.cshtml
> +
лишні пусті рядки

2021-08-09 19:35 UTC, XashDM commented on sports_hub/sports_hub/Views/AdminPage/FooterConfig/_EditContactUs.cshtml
> +
Лишні пусті рядки

2021-08-10 21:00 UTC, ZarechOleksii commented on sports_hub/sports_hub/Services/Implementations/FooterConfig/FooterConfigService.cs
> +            return _context.FooterPages.ToList().Find(p => p.Id == id);
Тут через те що ти викликаєш toList в тебе йде кверя на отримання всіх футерПейджес і тільки тоді вони фільтруються. Якщо ти зробиш щось по типу FooterPages.FirstOrDefault( лямбда вираз), тоді в тебе це відбудеться за один запит до бд і не потрібно буде додатково фільтрувати.

2021-08-10 21:00 UTC, ZarechOleksii commented on sports_hub/sports_hub/Services/Implementations/FooterConfig/FooterConfigService.cs
> +            return _context.FooterPages.ToList().Find(p => p.Name == name);
Те саме що попереднє

2021-08-11 08:39 UTC, XashDM commented on sports_hub/sports_hub/Services/Implementations/FooterConfig/FooterConfigService.cs
> +        private readonly ApplicationContext _context;
new line after private field

2021-08-11 08:42 UTC, XashDM commented on sports_hub/sports_hub/Services/Implementations/FooterConfig/FooterConfigService.cs
> +            return _context.FooterPages.ToList().Find(p => p.Id == id);
Agree with Oleksii - what you are doing now - you get all records from Database and then you are filtering.

2021-08-11 10:33 UTC, XashDM commented on sports_hub/sports_hub/Models/Entities/FooterPage.cs
> +        public bool Visible { get; set; }
Group properties together - no empty lines between

2021-08-11 10:34 UTC, XashDM commented on sports_hub/sports_hub/Models/ApplicationContext.cs
>          }
add empty line after constructor

2021-08-11 10:39 UTC, XashDM commented on sports_hub/sports_hub/Controllers/AdminPageController.cs
> +        private readonly FooterConfigService _footer_provider;
Add empty line before constructor

2021-08-11 10:40 UTC, XashDM commented on sports_hub/sports_hub/Controllers/AdminPageController.cs
> +
redundant empty line

2021-08-11 10:41 UTC, XashDM commented on sports_hub/sports_hub/Controllers/AdminPageController.cs
> +        }
add empty line

2021-08-11 10:41 UTC, XashDM approved these changes
Hi Maria, please fix comments. You can merge after that

2021-08-12 06:49 UTC, ZarechOleksii requested changes

2021-08-13 07:05 UTC, ZarechOleksii approved these changes

2021-08-13 08:33 UTC, merged